# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Yoakum Self Storage - Yoakum, Texas"
description: > # this means to ignore newlines until "email:"
   Meeting your Yoakum self storage needs with professional customer service and a secure location.

email: tim@512re.com
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Tim Hendricks'
author: 'Tim Hendricks'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://www.yoakumselfstorage.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@yoakumselfstorage'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/yoakumselfstorage
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
