# Site settings
title: Yoakum Self Storage
email: tim@512re.com
url: https://www.yoakumselfstorage.com
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#FDEB60'

# Footer settings
footer: Yoakum Self Storage

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/yoakumselfstorage
  - title: facebook
    url: https://www.facebook.com/yoakumselfstorage

# Build settings
markdown: kramdown
permalink: pretty
